apiVersion: v1
kind: Pod
metadata:
  name: frontend-app
spec:
  containers:
    - name: frontend-container
      image: nginx:alpine 
      resources:
        requests:
          cpu: "50m"     
          memory: "64Mi"   
--- 
apiVersion: v1
kind: Pod
metadata:
  name: backend-api
spec:
  containers:
    - name: backend-container
      image: golang:1.21-alpine
      command: ["sleep", "3600"] 
      resources:
        requests:
          cpu: "250m"     
          memory: "128Mi" 
--- 
apiVersion: v1
kind: Pod
metadata:
  name: cache-service
spec:
  containers:
    - name: cache-container
      image: redis:alpine 
      resources:
        requests:
          cpu: "100m"     
          memory: "256Mi"  

apiVersion: v1
kind: Pod
metadata: 
  name: nginx-test-pod
spec:
  containers: 
    - name: nginx-webserver
      image: nginx:1.21
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"